name: cupertino_setting_control
description: Wrapper for multiple kind of Cupertino Inputs (Textfield, Dropdown, Slider)
version: 1.1.0
homepage: https://github.com/Rodiii/flutter_cupertino_setting_control
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_range_slider_improved: ^2.0.1
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
