name: cupertino_setting_control
description: Wrapper for multiple kind of Cupertino Inputs (Textfield, Dropdown, Slider)
version: 1.0.0+1
homepage: https://github.com/Rodiii/flutter_cupertino_setting_control
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_range_slider: ^1.0.1
  url_launcher: ^5.4.5
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
