name: cupertino_setting_control
description: Wrapper for multiple kind of Cupertino Inputs (Textfield, Dropdown, Slider)
version: 1.0.3
homepage: https://github.com/Rodiii/flutter_cupertino_setting_control
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_range_slider: ^1.0.1
  url_launcher: ^6.0.3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
